In [5]:
import pandas as pd
import numpy as np

In [6]:
 # import & export - csv, excel,json 
# for ms excel
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\ab tayyab\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ab tayyab\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [7]:
import openpyxl

In [8]:
df = pd.read_csv("./files/retail_sales.csv",
                parse_dates = ["Date"],
                dtype={
                    "Category": "category",
                    "Region":"category"
                })
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [9]:
clean_df = df[df["Sales"]>0] # remove invalid rows
subset = clean_df[["Date","Category","Sales","Region"]]

In [10]:
subset.to_excel("./files/subset_sales.xlsx",sheet_name='sales')
subset.to_json("./files/subset_sales.json",
              orient="records",
              date_format="iso")
print("Files export!")
subset.info()

Files export!
<class 'pandas.core.frame.DataFrame'>
Index: 1778 entries, 0 to 1824
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1778 non-null   datetime64[ns]
 1   Category  1774 non-null   category
 2   Sales     1778 non-null   float64
 3   Region    1775 non-null   category
dtypes: category(2), datetime64[ns](1), float64(1)
memory usage: 110.2 KB

In [11]:
# handling data types and type converion 
df = pd.read_csv("./files/retail_sales.csv",
                parse_dates = ["Date"],
                dtype={
                    "Category": "category"
                })
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB

In [12]:
df['Profit']=pd.to_numeric(df['Profit']) # convert age to numeric
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB

In [13]:
# convert city to category 
df['Region']=df['Region'].astype('category')
df.info()
print(df['Region'].memory_usage(deep=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB
2395

In [14]:
# handling missing data
df = pd.read_csv(
    "./files/retail_sales.csv",
    parse_dates = ["Date"],
    dtype={
        "Category":"category",
        "Region":"category"
    }
)
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [16]:
print(df.isna().sum()) # detect missing values

Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64

In [17]:
# fill missing age with median. we use statistic function mean, median, mode: for numerical column we use mean and median and for categorical value we use mode.
df['Sales']=df['Sales'].fillna(df['Sales'].median())

In [18]:
# fill value with mode
df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mode()[0])

In [19]:
# fill with mode
df['Category']=df['Category'].fillna(df['Category'].mode()[0])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1825 non-null   category
 2   Sales     1825 non-null   float64
 3   Quantity  1825 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [21]:
print(df.isna().sum()) # detect missing values

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      5
dtype: int64

In [22]:
df.dropna(subset=['Region'],inplace=True)

In [23]:
print(df.isna().sum()) # detect missing values

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
dtype: int64

In [24]:
# String and text cleaning 
df = pd.DataFrame({
    'Category':['Electronics','furniture','Home-Appliance',' electronics','Furniture']
})
print(df)

         Category
0     Electronics
1       furniture
2  Home-Appliance
3     electronics
4       Furniture

In [25]:
# stripe spaces and convert tp lowercase
df['Category_clean']= df['Category'].str.strip().str.lower()
print(df)

         Category  Category_clean
0     Electronics     electronics
1       furniture       furniture
2  Home-Appliance  home-appliance
3     electronics     electronics
4       Furniture       furniture

In [26]:
# replace hyphen with space
df['Category_clean']= df['Category_clean'].str.replace('-',' ')
print(df)

         Category  Category_clean
0     Electronics     electronics
1       furniture       furniture
2  Home-Appliance  home appliance
3     electronics     electronics
4       Furniture       furniture

In [27]:
# sotring and ranking data 
df = pd.read_csv(
    "./files/retail_sales.csv",
    parse_dates = ["Date"],
    dtype={
        "Category":"category",
        "Region":"category"
    }
)
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [28]:
# sort by age ascending, then salary descending
df_sorted = df.sort_values(by=['Quantity','Sales'],ascending=[False,True])
print("Sorted the Dataframe")
df_sorted.head()

Sorted the Dataframe

           Date    Category       Sales  Quantity      Profit Region
312  2023-03-04  Home Goods    0.000000      19.0    0.000000   West
528  2023-04-16      Sports    0.000000      19.0  270.577388   West
1708 2023-12-08      Sports  227.942727      19.0   61.534381  North
571  2023-04-25    Clothing  361.006937      19.0   57.285585   West
1213 2023-08-31      Sports  368.305917      19.0   73.419555   West

In [29]:
# rank salary within age groups
df['Sales_rank']=df.groupby('Quantity')['Sales'].rank(method='dense',ascending=False)
print("sales rank within quantity group \n",df)

sales rank within quantity group
            Date     Category        Sales  Quantity      Profit Region  \
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

      Sales_rank
0           29.0
1           56.0
2            7.0
3           24.0
4           68.0
...          ...
1820        30.0
1821        88.0
1822        32.0
1823        38.0
1824        73.0

[1825 rows x 7 columns]

In [30]:
# Merging and joining Dataframes:  inner join, left join, right join, outer join.
#sample Dataframes
customers = pd.DataFrame({
    'CustomerID':[1,2,3],
    'Name':['Alice','Bob','Charlie']
})
orders = pd.DataFrame({
    'OrderID':[101,102,103,104],
    'CustomerID':[1,2,2,3],
    'Amount':[205,150,200,300]
})
# inner merge on customerID 
df_inner = pd.merge(customers,orders,on='CustomerID',how='inner')
print("Inner merge: \n",df_inner)

Inner merge:
    CustomerID     Name  OrderID  Amount
0           1    Alice      101     205
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300

In [31]:
# left merge
df_left = pd.merge(customers,orders,on='CustomerID',how='left')
print("Left merge: \n",df_left)

Left merge:
    CustomerID     Name  OrderID  Amount
0           1    Alice      101     205
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300

In [32]:
# concatenate rows example
df_concat = pd.concat([customers,customers])
print("Left merge: \n",df_concat)

Left merge:
    CustomerID     Name
0           1    Alice
1           2      Bob
2           3  Charlie
0           1    Alice
1           2      Bob
2           3  Charlie

In [33]:
# applying function-apply,map & pipe 
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [34]:
# map(), label high value orders
df["payment_type"]=df["payment_method"].map({
    "Card":"Digital",
    "Wallet":"Digital",
    "COD":"Cash"
})

In [35]:
#verify
df["payment_type"].unique() # check unique value

array(['Digital', 'Cash'], dtype=object)

In [36]:
df[["payment_method","payment_type"]].head() # compare before vs after

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [37]:
df.groupby("payment_type").size() # business sanity check

payment_type
Cash       1774
Digital    3226
dtype: int64

In [38]:
# apply() - create revenue category
def revenue_category(row):
    if(row)["revenue"]>500:
        return "High"
    elif row["revenue"]>=200:
        return "Medium"
    else:
        return "Low"
df["revenue_category"]= df.apply(revenue_category,axis=1)

In [39]:
# verify
df["revenue_category"].value_counts() # check cetegory

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [40]:
df[["revenue","revenue_category"]].sample(10) # validate logoc manually

      revenue revenue_category
4536   101.98              Low
2499   223.82           Medium
74     222.79           Medium
3861  1459.41             High
3837  1440.41             High
3021   788.37             High
25     140.49              Low
2888    75.67              Low
4679   497.11           Medium
1600   581.50             High

In [41]:
# pipe() - method chaining
def add_profit(data):
    data["profit"]=data["revenue"]*0.20
    return data
def add_net_revenue(data):
    data["net_revenue"]=data["revenue"]-data["profit"]
    return data
df=(
df
.pipe(add_profit)
.pipe(add_net_revenue)
)

In [42]:
# verify
df[["revenue","profit","net_revenue"]].head()  # check new column

   revenue   profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848